apiVersion: v1
kind: Service
metadata:
  name: testgetaway
  namespace: default
  labels:
    app: testgetaway
spec:
  selector:
    app: testgetaway
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
