apiVersion: v1
kind: Secret
metadata:
  name: testmicro-postgresql
  namespace: default
  labels:
    app: testmicro-postgresql
type: Opaque
data:
  postgresql-password: MDljZmY4MzBkOTU4ZjNmMTI2NjRlOThmMDZkYmZkMmQ0N2U4Y2RkMGU2NjNlMDlmM2U2NjZiYjY0MTg5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmicro-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testmicro-postgresql
  template:
    metadata:
      labels:
        app: testmicro-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:13.4
          env:
            - name: POSTGRES_USER
              value: testmicro
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: testmicro-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: testmicro-postgresql
  namespace: default
spec:
  selector:
    app: testmicro-postgresql
  ports:
    - port: 5432
